name: algorithms
description: Implementation of algorithms with Dart.
# version: 1.0.0
# homepage: https://www.example.com
# author: Mafinar K <mafinar@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.15.4
  effective_dart: ^1.2.0
